### ISSUE TITLE
CSV file for each league

### ISSUE THREAD

**Issue by ghost** [vnherdeiro/transfermarkt-scraping#2]
I tried to save the csv file by the league. But im missing something. Im able to create csv for each league but some of the lines in the files repeats. For example, if i have two files LaLiga, Premier League. LaLiga contains the player for LaLiga. However the premier league file also have LaLiga players in it.

**Comment by vnherdeiro** [comment]
Hi there,

First, I am not sure to understand the issue you are facing. Can you share the lines of code you share for splitting the dataframe by league? Because I don't see how there could be an overlap between two leagues.

When you mean same player in LaLiga and in Premier League, do you mean same name? Because then, two distinct players can share the same name. In the `StrikerPerformance.csv` in `master`, there 3 Wanderson and 2 Leandrinho because different Brazilian players are using and being identified by the same nickname.

Let me know if this helps.

**Comment by ghost** [comment]
Hey,
I change the file a little bit. I want to organize the csv files by leagues since i dont want a large csv file. So I made changes to line 50 and 58. 
![tm](https://user-images.githubusercontent.com/14948884/35656989-2206ed40-06c8-11e8-9f77-49e3696de9e0.png)

I was scraping only 2 league, Premier League then LaLiga. After scrapping this two leagues it created two . 
![eplsize](https://user-images.githubusercontent.com/14948884/35657086-a787287c-06c8-11e8-8e87-ac370e756402.png)

![ligasize](https://user-images.githubusercontent.com/14948884/35657106-b912bd72-06c8-11e8-8d1c-646803691d96.png)
if you look at the bottom corner, LaLiga playerdata files is much larger that the premier league (303.3kb)
What's happening is that all of players from the premier league along with the information of laliga is being added to the file. The premier league file contains only premier league data since it was scrapped first. The league file is created immediately after the league is scrapped

**Comment by vnherdeiro** [comment]
I think I see the issue, the problem in your code is that `PlayerProfiles` does not get 'flushed' at each iteration of your league loop.

You could get there by modifying lines 41-44 of my `main.py` by

```
	for leagueName, leagueUrl in LeagueUrlDic.items():
		print( "Scraping the %s..." %leagueName)
		LeagueData = League( leagueName, leagueUrl, scraper)
	        PlayerProfiles = [player.PlayerData for team in LeagueData.TeamsData for player in team.PlayersData]
         	df = pd.DataFrame( PlayerProfiles)
        	df.to_csv("%s_StrikerPerformance.csv" %leagueName, index=False)
```

**Comment by ghost** [comment]
How would I do that?  What do you mean by flushed?

-------- Original message --------

**Comment by vnherdeiro** [comment]
Flushed was not the best choice of words, I meant emptied. But looking back at your code, it is the `LeaguesData` that needs to be emptied. At the beginning of your `for` loop (the one in your code screenchot), add the line `LeaguesData = []`.

**Comment by ghost** [comment]
Thanks
